WDL-OL/IPlug: IGraphicsPathBase Class Reference
IGraphicsPathBase Class Reference abstract
Public Member Functions
IGraphicsPathBase (IDelegate &dlg, int w, int h, int fps)
void DrawRotatedBitmap (IBitmap &bitmap, int destCtrX, int destCtrY, double angle, int yOffsetZeroDeg, const IBlend *pBlend) override
Draw a bitmap (raster) image to the graphics context with rotation.
void DrawRotatedMask (IBitmap &base, IBitmap &mask, IBitmap &top, int x, int y, double angle, const IBlend *pBlend) override
Draw a rotated, masked bitmap to the graphics context.
void DrawLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend) override
Draw a line to the graphics context.
void DrawTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend) override
Draw a triangle to the graphics context.
void DrawRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
Draw a rectangle to the graphics context.
void DrawRoundRect (const IColor &color, const IRECT &rect, float corner, const IBlend *pBlend) override
Draw a circle to the graphics context.
void DrawConvexPolygon (const IColor &color, float *x, float *y, int nPoints, const IBlend *pBlend) override
Draw a convex polygon to the graphics to the graphics context.
void DrawArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend) override
Draw an arc to the graphics context.
void DrawCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend) override
Draw a circle to the graphics context.
void DrawDottedRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
Draw a dotted rectangle to the graphics context.
void FillTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend) override
Fill a triangle in the graphics context with a color.
void FillRect (const IColor &color, const IRECT &rect, const IBlend *pBlend) override
Fill a rectangular region of the graphics context with a color.
void FillRoundRect (const IColor &color, const IRECT &rect, float corner, const IBlend *pBlend) override
Fill a rounded rectangle in the graphics context with a color.
void FillConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend) override
Fill a convex polygon in the graphics context with a color.
void FillArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend) override
Fill an arc segment in the graphics context with a color.
void FillCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend) override
Fill a circle in the graphics context with a color.
void DrawPoint (const IColor &color, float x, float y, const IBlend *pBlend) override
Fill a point with a color.
void ForcePixel (const IColor &color, int x, int y) override
Fill a point/pixel with a color.
bool HasPathSupport () const override
void PathTriangle (float x1, float y1, float x2, float y2, float x3, float y3) override
void PathRect (const IRECT &rect) override
void PathRoundRect (const IRECT &rect, float cr) override
void PathCircle (float cx, float cy, float r) override
void PathConvexPolygon (float *x, float *y, int npoints) override
virtual void PathStateSave ()=0
virtual void PathStateRestore ()=0
virtual void PathTransformTranslate (float x, float y)=0
virtual void PathTransformScale (float scale)=0
virtual void PathTransformRotate (float angle)=0
void DrawSVG (ISVG &svg, const IRECT &dest, const IBlend *pBlend) override
Draw an SVG image to the graphics context.
void DrawRotatedSVG (ISVG &svg, float destCtrX, float destCtrY, float width, float height, double angle, const IBlend *pBlend) override
Draw an SVG image to the graphics context with rotation.
Public Member Functions inherited from IGraphics
virtual void BeginFrame ()
virtual void EndFrame ()
virtual void ViewInitialized (void *pLayer)
virtual void SetDisplayScale (int scale)
Called by the platform IGraphics class when UI created and when moving to a new screen with different DPI, implementations in draw class must call the base implementation.
virtual void DrawBitmap (IBitmap &bitmap, const IRECT &bounds, int srcX, int srcY, const IBlend *pBlend=0)=0
Draw a bitmap (raster) image to the graphics context.
virtual bool DrawText (const IText &text, const char *str, IRECT &bounds, bool measure=false)=0
Draw some text to the graphics context (or measure some text)
virtual bool MeasureText (const IText &text, const char *str, IRECT &bounds)=0
Measure the rectangular region that some text will occupy.
virtual IColor GetPoint (int x, int y)=0
Get the color of a point in the graphics context.
virtual void * GetData ()=0
Gets a void pointer to IGraphics Draw Class context data (e.g raw framebuffer).
virtual const char * GetDrawingAPIStr ()=0
virtual void ClipRegion (const IRECT &bounds)
This is overridden in some IGraphics drawing classes to clip drawing to a rectangular region.
virtual void ResetClipRegion ()
This is overridden in some IGraphics drawing classes so you can reset clipping after drawing a shape.
virtual IBitmap LoadBitmap (const char *name, int nStates=1, bool framesAreHorizontal=false)
virtual IBitmap ScaleBitmap (const IBitmap &srcbitmap, const char *cacheName, int targetScale)
virtual void RetainBitmap (const IBitmap &bitmap, const char *cacheName)
virtual void ReleaseBitmap (const IBitmap &bitmap)
IBitmap GetScaledBitmap (IBitmap &src)
virtual void OnDisplayScale ()
This method is called when display on which the UI resides changes scale, i.e.
virtual void RenderDrawBitmap ()
Called by some drawing API classes to finally blit the draw bitmap onto the screen.
void DrawBitmap (IBitmap &bitmap, const IRECT &bounds, int frame=1, const IBlend *pBlend=0)
Draws a bitmap into the graphics context.
void DrawBitmapedText (IBitmap &bitmap, IRECT &bounds, IText &text, IBlend *pBlend, const char *str, bool vCenter=true, bool multiline=false, int charWidth=6, int charHeight=12, int charOffset=0)
Draws mono spaced bitmap text.
void DrawVerticalLine (const IColor &color, const IRECT &bounds, float x, const IBlend *pBlend=0)
Draw a vertical line, within a rectangular region of the graphics context.
void DrawHorizontalLine (const IColor &color, const IRECT &bounds, float y, const IBlend *pBlend=0)
Draw a horizontal line, within a rectangular region of the graphics context.
void DrawVerticalLine (const IColor &color, float xi, float yLo, float yHi, const IBlend *pBlend=0)
/todo
void DrawHorizontalLine (const IColor &color, float yi, float xLo, float xHi, const IBlend *pBlend=0)
/todo
void DrawRadialLine (const IColor &color, float cx, float cy, float angle, float rMin, float rMax, const IBlend *pBlend=0)
Draw a radial line to the graphics context, useful for pointers on dials.
void DrawGrid (const IColor &color, const IRECT &bounds, int gridSizeH, int gridSizeV, const IBlend *pBlend=0)
Draw a grid to the graphics context.
virtual void PathClear ()
virtual void PathStart ()
virtual void PathClose ()
void PathLine (float x1, float y1, float x2, float y2)
void PathRadialLine (float cx, float cy, float angle, float rMin, float rMax)
virtual void PathArc (float cx, float cy, float r, float aMin, float aMax)
virtual void PathMoveTo (float x, float y)
virtual void PathLineTo (float x, float y)
virtual void PathCurveTo (float x1, float y1, float x2, float y2, float x3, float y3)
virtual void PathStroke (const IPattern &pattern, float thickness, const IStrokeOptions &options=IStrokeOptions(), const IBlend *pBlend=0)
virtual void PathFill (const IPattern &pattern, const IFillOptions &options=IFillOptions(), const IBlend *pBlend=0)
virtual void HideMouseCursor ()
Call to hide the mouse cursor.
virtual void ShowMouseCursor ()
Call to show the mouse cursor when it is hidden.
virtual void MoveMouseCursor (float x, float y)=0
Force move the mouse cursor to a specific position in the graphics context.
void SetTabletInput (bool tablet)
Set by the platform class if the mouse input is coming from a tablet/stylus.
virtual void ForceEndUserEdit ()=0
Call to force end text entry (will cancel any half input text /todo check)
virtual void Resize (int w, int h, float scale)
/todo detailled description of how this works
virtual void * OpenWindow (void *pParentWnd)=0
Open a new platform view for this graphics context.
virtual void CloseWindow ()=0
Close the platform view for this graphics context.
virtual void * GetWindow ()=0
Get a pointer to the platform view for this graphics context return void pointer to platform window or view handle.
virtual bool WindowIsOpen ()
virtual bool GetTextFromClipboard (WDL_String &str)=0
Get text from the clipboard.
virtual void UpdateTooltips ()=0
Call this if you modify control tool tips at runtime.
virtual int ShowMessageBox (const char *str, const char *caption, int type)=0
Pop up a modal platform message box dialog.
virtual IPopupMenu * CreateIPopupMenu (IPopupMenu &menu, IRECT &bounds)=0
/todo
virtual void CreateTextEntry (IControl &control, const IText &text, const IRECT &bounds, const char *str="")=0
Create a platform text entry box.
virtual void PromptForFile (WDL_String &filename, WDL_String &path, EFileAction action=kFileOpen, const char *extensions=0)=0
Create a platform file prompt dialog to choose a file/directory path for opening/saving a file/directory.
virtual bool PromptForColor (IColor &color, const char *str="")=0
Create a platform color chooser dialog.
virtual bool OpenURL (const char *url, const char *msgWindowTitle=0, const char *confirmMsg=0, const char *errMsgOnFailure=0)=0
Open a URL in the platforms default browser.
virtual const char * GetPlatformAPIStr ()
virtual void HostPath (WDL_String &path)=0
virtual void PluginPath (WDL_String &path)=0
virtual void DesktopPath (WDL_String &path)=0
virtual void UserHomePath (WDL_String &path)=0
virtual void AppSupportPath (WDL_String &path, bool isSystem=false)=0
virtual void SandboxSafeAppSupportPath (WDL_String &path)=0
virtual void VST3PresetsPath (WDL_String &path, const char *mfrName, const char *pluginName, bool isSystem=true)
virtual bool RevealPathInExplorerOrFinder (WDL_String &path, bool select=false)=0
virtual void SetPlatformInstance (void *pInstance)
Used on Windows to set the HINSTANCE handle, which allows graphics APIs to load resources from the binary.
virtual void * GetPlatformInstance ()
Get a void pointer that can be cast back to HINSTANCE /todo what about Mac?
virtual void SetPlatformContext (void *pContext)
Set the platform draw context Used with IGraphicsLice (possibly others) in order to set the CoreGraphics draw context on macOS and the GDI HDC draw context handle on Windows.
void * GetPlatformContext ()
Get the platform draw context.
virtual bool OSFindResource (const char *filename, const char *type, WDL_String &result)=0
Find the full, absolute path of a resource based on it's filename (e.g.
IGraphics (IDelegate &dlg, int w, int h, int fps=0)
bool IsDirty (IRECT &bounds)
Called repeatedly at frame rate by the platform class to check what the graphics context says is dirty.
virtual void Draw (const IRECT &bounds)
Called by the platform class when an area needs to be redrawn.
virtual ISVG LoadSVG (const char *filename)
Load an SVG from disk.
void UpdatePeers (IControl *pCaller)
This method is called after interacting with a control, so that any other controls linked to the same parameter index, will also be set dirty, and have their values updated.
void PromptUserInput (IControl &control, IRECT &bounds)
Prompt for user input either using a text entry or pop up menu.
void SetControlValueFromStringAfterPrompt (IControl &control, const char *str)
Called by the platform class after returning from a prompt (typically a text entry) in order to update a control with a new value.
IPopupMenu * CreateIPopupMenu (IPopupMenu &menu, float x, float y)
/todo
void SetStrictDrawing (bool strict)
Enables strict drawing mode.
int Width () const
Gets the width of the graphics context.
int Height () const
Gets the height of the graphics context.
int WindowWidth () const
Gets the width of the graphics context including scaling /todo better explanation.
int WindowHeight () const
Gets the height of the graphics context including scaling /todo better explanation.
int FPS () const
Gets the drawing frame rate.
float GetScale () const
Gets the graphics context scaling factor.
float GetDisplayScale () const
Gets the display scaling factor.
IDelegate & GetDelegate ()
Gets a Reference to the delegate class that handles communication to and from this graphics context.
void AttachBackground (const char *filename)
Attach an IBitmapControl as the lowest IControl in the control stack to be the background for the graphics context.
void AttachPanelBackground (const IColor &color)
Attach an IPanelControl as the lowest IControl in the control stack to fill the background with a solid color.
void AttachKeyCatcher (IControl &control)
Attach a designated Key Catcher IControl.
int AttachControl (IControl *pControl)
Attach an IControl to the graphics context and add it to the top of the control stack.
IControl * GetControl (int idx)
int NControls () const
void HideControl (int paramIdx, bool hide)
void GrayOutControl (int paramIdx, bool gray)
void ClampControl (int paramIdx, double lo, double hi, bool normalized)
void SetAllControlsDirty ()
void OnMouseDown (float x, float y, const IMouseMod &mod)
void OnMouseUp (float x, float y, const IMouseMod &mod)
void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
bool OnMouseDblClick (float x, float y, const IMouseMod &mod)
void OnMouseWheel (float x, float y, const IMouseMod &mod, float delta)
bool OnKeyDown (float x, float y, int key)
bool OnMouseOver (float x, float y, const IMouseMod &mod)
void OnMouseOut ()
void OnDrop (const char *str, float x, float y)
void OnGUIIdle ()
int GetParamIdxForPTAutomation (float x, float y)
[AAX only] This can be called by the ProTools API class (e.g.
int GetLastClickedParamForPTAutomation ()
[AAX only]
void SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only] /todo
void PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily]
void HandleMouseOver (bool canHandle)
void ReleaseMouseCapture ()
void EnableTooltips (bool enable)
void AssignParamNameToolTips ()
Call this method in order to create tool tips for every IControl that show the associated parameter's name.
void ShowControlBounds (bool enable)
void ShowAreaDrawn (bool enable)
void EnableLiveEdit (bool enable, const char *file=0, int gridsize=10)
Live edit mode allows you to relocate controls at runtime in debug builds and save the locations to a predefined file (e.g.
IRECT GetDrawRect () const
Return the rectangular region of the graphics context marked for drawing.
IRECT GetBounds () const
Returns an IRECT that represents the entire UI bounds This is useful for programatically arranging UI elements by slicing up the IRECT using the various IRECT methods.
bool CanHandleMouseOver () const
int GetMouseOver () const
bool TooltipsEnabled () const
virtual void LoadFont (const char *name)
Additional Inherited Members
Protected Member Functions inherited from IGraphics
virtual APIBitmap * LoadAPIBitmap (const WDL_String &resourcePath, int scale)=0
virtual APIBitmap * ScaleAPIBitmap (const APIBitmap *pBitmap, int scale)=0
void SearchNextScale (int &sourceScale, int targetScale)
bool SearchImageResource (const char *name, const char *type, WDL_String &result, int targetScale, int &sourceScale)
APIBitmap * SearchBitmapInCache (const char *name, int targetScale, int &sourceScale)
Protected Attributes inherited from IGraphics
IDelegate & mDelegate
WDL_PtrList< IControl > mControls
IRECT mDrawRECT
void * mPlatformContext = nullptr
bool mCursorHidden = false
bool mTabletInput = false
Detailed Description
Definition at line 7 of file IGraphicsPathBase.h.
Member Function Documentation
void IGraphicsPathBase::DrawArc (const IColor & color, float cx, float cy, float r, float aMin, float aMax, const IBlend * pBlend) inline override virtual
Draw an arc to the graphics context.
Parameters
color The color to draw the shape with
cx The X coordinate in the graphics context of the centre of the circle on which the arc lies
cy The Y coordinate in the graphics context of the centre of the circle on which the arc lies
r The radius of the circle on which the arc lies
aMin the start angle of the arc at in degrees clockwise where 0 is up
aMax the end angle of the arc at in degrees clockwise where 0 is up
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 74 of file IGraphicsPathBase.h.
void IGraphicsPathBase::DrawCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend) inline override virtual
Draw a circle to the graphics context.
Parameters
color The color to draw the shape with
cx The X coordinate in the graphics context of the centre of the circle
cy The Y coordinate in the graphics context of the centre of the circle
r The radius of the circle
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 80 of file IGraphicsPathBase.h.
void IGraphicsPathBase::DrawConvexPolygon (const IColor & color, float * x, float * y, int nPoints, const IBlend * pBlend) inline override virtual
Draw a convex polygon to the graphics to the graphics context.
Parameters
color The color to draw the shape with
x Pointer to the first element in an array of X coordinates for the vertices of the polygon
y Pointer to the first element in an array of Y coordinates for the vertices of the polygon
nPoints The number of points in the coordinate arrays
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 68 of file IGraphicsPathBase.h.
void IGraphicsPathBase::DrawDottedRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend) inline override virtual
Draw a dotted rectangle to the graphics context.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 86 of file IGraphicsPathBase.h.
void IGraphicsPathBase::DrawLine (const IColor & color, float x1, float y1, float x2, float y2, const IBlend * pBlend) inline override virtual
Draw a line to the graphics context.
Parameters
color The color to draw the shape with
x1 The X coordinate in the graphics context of the start of the line
y1 The Y coordinate in the graphics context of the start of the line
x2 The X coordinate in the graphics context of the end of the line
y2 The Y coordinate in the graphics context of the end of the line
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 43 of file IGraphicsPathBase.h.
void IGraphicsPathBase::DrawPoint (const IColor & color, float x, float y, const IBlend * pBlend) inline override virtual
Fill a point with a color.
On 1:1 screens a point is a pixel. /todo is this correct? what about high DPI displays
Parameters
color The color to fill the point with
x The X coordinate in the graphics context at which to draw
y The Y coordinate in the graphics context at which to draw
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 133 of file IGraphicsPathBase.h.
References FillRect().
Referenced by ForcePixel().
void IGraphicsPathBase::DrawRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend) inline override virtual
Draw a rectangle to the graphics context.
Parameters
bounds The rectangular area in which to draw the shape
color The color to draw the shape to draw the shape with
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 56 of file IGraphicsPathBase.h.
void IGraphicsPathBase::DrawRotatedBitmap (IBitmap & bitmap, int destCentreX, int destCentreY, double angle, int yOffsetZeroDeg, const IBlend * pBlend) inline override virtual
Draw a bitmap (raster) image to the graphics context with rotation.
Parameters
bitmap The bitmap image to draw to the graphics context
destCentreX The X coordinate in the graphics context of the centre point at which to rotate the image around. /todo check this
destCentreY The Y coordinate in the graphics context of the centre point at which to rotate the image around. /todo check this
angle The angle of rotation in degrees
yOffsetZeroDeg /todo
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 14 of file IGraphicsPathBase.h.
References IGraphics::DrawBitmap(), IBitmap::H(), and IBitmap::W().
void IGraphicsPathBase::DrawRotatedMask (IBitmap & base, IBitmap & mask, IBitmap & top, int x, int y, double angle, const IBlend * pBlend) inline override virtual
Draw a rotated, masked bitmap to the graphics context.
Parameters
base The base bitmap image to draw to the graphics context /todo explain base
mask The mask bitmap image to draw to the graphics context /todo explain mask
top The bitmap image to draw to the graphics context /todo explain top
x The X coordinate in the graphics context at which to draw
y The Y coordinate in the graphics context at which to draw
angle The angle to rotate the bitmap mask at in degrees clockwise
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 28 of file IGraphicsPathBase.h.
References IGraphics::DrawBitmap(), IBitmap::H(), and IBitmap::W().
void IGraphicsPathBase::DrawRotatedSVG (ISVG & svg, float destCentreX, float destCentreY, float width, float height, double angle, const IBlend * pBlend) inline override virtual
Draw an SVG image to the graphics context with rotation.
Parameters
svg The SVG image to draw to the graphics context
destCentreX The X coordinate in the graphics context of the centre point at which to rotate the image around. /todo check this
destCentreY The Y coordinate in the graphics context of the centre point at which to rotate the image around. /todo check this
width /todo
height /todo
angle The angle to rotate the bitmap mask at in degrees clockwise
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 210 of file IGraphicsPathBase.h.
References DrawSVG().
void IGraphicsPathBase::DrawRoundRect (const IColor & color, const IRECT & bounds, float cr, const IBlend * pBlend) inline override virtual
Draw a circle to the graphics context.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
cr The corner width in pixels
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 62 of file IGraphicsPathBase.h.
void IGraphicsPathBase::DrawSVG (ISVG & svg, const IRECT & bounds, const IBlend * pBlend) inline override virtual
Draw an SVG image to the graphics context.
Parameters
svg The SVG image to the graphics context
bounds The rectangular region to draw the image in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 196 of file IGraphicsPathBase.h.
References IGraphics::ClipRegion().
Referenced by DrawRotatedSVG().
void IGraphicsPathBase::DrawTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend) inline override virtual
Draw a triangle to the graphics context.
Parameters
color The color to draw the shape with
x1 The X coordinate in the graphics context of the first vertex
y1 The Y coordinate in the graphics context of the first vertex
x2 The X coordinate in the graphics context of the second vertex
y2 The Y coordinate in the graphics context of the second vertex
x3 The X coordinate in the graphics context of the third vertex
y3 The Y coordinate in the graphics context of the third vertex
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 50 of file IGraphicsPathBase.h.
void IGraphicsPathBase::FillArc (const IColor & color, float cx, float cy, float r, float aMin, float aMax, const IBlend * pBlend) inline override virtual
Fill an arc segment in the graphics context with a color.
Parameters
color The color to fill the shape with
cx The X coordinate in the graphics context of the centre of the circle on which the arc lies
cy The Y coordinate in the graphics context of the centre of the circle on which the arc lies
r The radius of the circle on which the arc lies
aMin the start angle of the arc at in degrees clockwise where 0 is up
aMax the end angle of the arc at in degrees clockwise where 0 is up
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 119 of file IGraphicsPathBase.h.
void IGraphicsPathBase::FillCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend) inline override virtual
Fill a circle in the graphics context with a color.
Parameters
color The color to fill the shape with
cx The X coordinate in the graphics context of the centre of the circle
cy The Y coordinate in the graphics context of the centre of the circle
r The radius of the circle
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 127 of file IGraphicsPathBase.h.
void IGraphicsPathBase::FillConvexPolygon (const IColor & color, float * x, float * y, int nPoints, const IBlend * pBlend) inline override virtual
Fill a convex polygon in the graphics context with a color.
Parameters
color The color to fill the shape with
x Pointer to the first element in an array of X coordinates for the vertices of the polygon
y Pointer to the first element in an array of Y coordinates for the vertices of the polygon
nPoints The number of points in the coordinate arrays
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 113 of file IGraphicsPathBase.h.
void IGraphicsPathBase::FillRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend) inline override virtual
Fill a rectangular region of the graphics context with a color.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 101 of file IGraphicsPathBase.h.
Referenced by DrawPoint().
void IGraphicsPathBase::FillRoundRect (const IColor & color, const IRECT & bounds, float cr, const IBlend * pBlend) inline override virtual
Fill a rounded rectangle in the graphics context with a color.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
cr The corner radius in pixels
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 107 of file IGraphicsPathBase.h.
void IGraphicsPathBase::FillTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend) inline override virtual
Fill a triangle in the graphics context with a color.
Parameters
color The color to fill the shape with
x1 The X coordinate in the graphics context of the first vertex
y1 The Y coordinate in the graphics context of the first vertex
x2 The X coordinate in the graphics context of the second vertex
y2 The Y coordinate in the graphics context of the second vertex
x3 The X coordinate in the graphics context of the third vertex
y3 The Y coordinate in the graphics context of the third vertex
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 95 of file IGraphicsPathBase.h.
void IGraphicsPathBase::ForcePixel (const IColor & color, int x, int y) inline override virtual
Fill a point/pixel with a color.
/todo what about high DPI displays
Parameters
color The color to fill the shape with
x The X coordinate in the graphics context at which to draw
y The Y coordinate in the graphics context at which to draw
Implements IGraphics.
Definition at line 138 of file IGraphicsPathBase.h.
References DrawPoint().
The documentation for this class was generated from the following file:
IGraphicsPathBase.h